<?php

// autoload.php @generated by Composer

require_once  '../composer/autoload_real.php';
//require_once implode([__DIR__, 'composer', 'autoload_real.php'], DIRECTORY_SEPARATOR);

return ComposerAutoloaderInit887fe7c3e68b8fe16f44cca87b7bba27::getLoader();
